### ISSUE TITLE
[jnigen] Detect mvn missing error and fail gracefully

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1234]
```
$ dart --enable-experiment=native-assets run jnigen --config jnigen_config.yaml 
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) INFO: execute mvn compile --batch-mode --update-snapshots -f /Users/dacoharkes/.pub-cache/hosted/pub.dev/jnigen-0.9.3/java/pom.xml

/bin/sh: mvn: command not found

maven exited with 127
Unhandled exception:
PathNotFoundException: Deletion failed, path = './.dart_tool/jnigen/target' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:180:7)
<asynchronous suspension>
#2      buildApiSummarizer (package:jnigen/src/tools/build_summarizer.dart:51:5)
<asynchronous suspension>
#3      buildSummarizerIfNotExists (package:jnigen/src/tools/build_summarizer.dart:74:5)
<asynchronous suspension>
#4      generateJniBindings (package:jnigen/src/generate_bindings.dart:26:3)
<asynchronous suspension>
#5      main (file:///Users/dacoharkes/.pub-cache/hosted/pub.dev/jnigen-0.9.3/bin/jnigen.dart:18:3)
<asynchronous suspension>
```

We should probably not fail with deletion failed if mvn is missing.

**Comment by jwill** [comment]
This is obsolete. Maven was removed as a dependency with the migration to gradle last year.

https://github.com/dart-lang/native/commit/9c58064b8b728f0543cd50b10187d9ca7c16912e
