### ISSUE TITLE
Fail to compile the example in the repository: `Configuration is not in the right format. FormatExceptions: [FormatException: No value was provided for required key: package_name`

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/native#818]
Hi thanks for the toolchain! However I fail to compile the example. Reproduction: git clone, and cd into `pkgs/native_assets_cli/example/native_add_library` Execute `dart --enable-experiment=native-assets test` and get:

<details>

```shell
(base) ➜  native_add_library git:(main) dart --enable-experiment=native-assets test
Unhandled exception:
FormatException: Configuration is not in the right format. FormatExceptions: [FormatException: No value was provided for required key: package_name, #0      Config._throwIfNull (package:cli_config/src/config.dart:591:7)
#1      Config.string (package:cli_config/src/config.dart:213:5)
#2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:321:41)
#3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:249:10)
#4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:286:24)
<asynchronous suspension>
#5      main (file:///Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/build.dart:15:23)
<asynchronous suspension>
]
#0      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:257:7)
#1      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:286:24)
<asynchronous suspension>
#2      main (file:///Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/build.dart:15:23)
<asynchronous suspension>
Building native assets for package:native_add_library failed.
build.dart returned with exit code: 255.
To reproduce run:
/Users/tom/fvm/versions/3.16.0/bin/cache/dart-sdk/bin/dart --packages=/Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/.dart_tool/package_config.json /Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/build.dart --config=/Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/.dart_tool/native_assets_builder/9fe3bb4141b182a788cfb7907563ade2/config.yaml
stderr:
Unhandled exception:
FormatException: Configuration is not in the right format. FormatExceptions: [FormatException: No value was provided for required key: package_name, #0      Config._throwIfNull (package:cli_config/src/config.dart:591:7)
#1      Config.string (package:cli_config/src/config.dart:213:5)
#2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:321:41)
#3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:249:10)
#4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:286:24)
<asynchronous suspension>
#5      main (file:///Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/build.dart:15:23)
<asynchronous suspension>
]
#0      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:257:7)
#1      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:286:24)
<asynchronous suspension>
#2      main (file:///Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_library/build.dart:15:23)
<asynchronous suspension>

stdout:

        
Error: Compiling native assets failed.
```

</details>

Then I realized it is because v0.3.0 has a breaking change. Thus I make this issue, such that people who is in the same situation as me (using the stable Dart 3.2 + the in-tree example, coming from https://dart.dev/guides/libraries/c-interop#native-assets webpage), can search and find this page and avoid wasting a few minutes finding out manually why :)

By the way, maybe it is better to add a hint in https://dart.dev/guides/libraries/c-interop#native-assets to hint users about this?

**Comment by dcharkes** [comment]
While this feature is experimental, we might need to break the protocol between the Dart/Flutter SDK and the `build.dart` scripts a couple of more times while we iron out the protocol.

Our goal is to bump the protocol version number when making such changes.

https://github.com/dart-lang/native/blob/893433ee9e7a5bfbc8ebb52840c9448bda124f2c/pkgs/native_assets_cli/lib/src/model/build_config.dart#L242

However, I think have forgotten to do that in https://github.com/dart-lang/native/pull/150. Sorry for the confusion! 🙊 With that version being bumped there should be a clearer error message.
