### ISSUE TITLE
[jnigen][infra] Flaky NoClassDefFoundError

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#838]
I believe I have seen this error flaky on the CI before.

I'll hit rerun on the CI to see if it turns green, but we should try to squash the flakiness!

```
❌ test\generated_runtime_test.dart: kotlin_test_c_based Suspend functions (failed)
  Exception in Java code called through JNI: java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/SuspendFun
  
  java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/SuspendFun
  Caused by: java.lang.ClassNotFoundException: com.github.dart_lang.jnigen.SuspendFun
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
  
  
  package:jni/src/accessors.dart 116:5                      JniAccessorWrappers.throwException
  package:jni/src/accessors.dart 16:19                      _check
  package:jni/src/accessors.dart 21:19                      JniResultMethods.check
  package:jni/src/accessors.dart 59:5                       JniResultMethods.object
  test\kotlin_test\c_based\dart_bindings\kotlin.dart 52:39  new SuspendFun
  test\kotlin_test\runtime_test_registrant.dart 16:28       registerTests.<fn>.<fn>.<fn>
  package:ffi/src/arena.dart 124:31                         using
  test\kotlin_test\runtime_test_registrant.dart 15:13       registerTests.<fn>.<fn>
✅ test\generated_runtime_test.dart: jackson_core_test_c_based simple json parsing test
✅ test\generated_runtime_test.dart: jackson_core_test_c_based parsing invalid JSON throws JniException
❌ test\generated_runtime_test.dart: kotlin_test_dart_only Suspend functions (failed)
  Exception in Java code called through JNI: java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/SuspendFun
  
  java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/SuspendFun
  Caused by: java.lang.ClassNotFoundException: com.github.dart_lang.jnigen.SuspendFun
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
  
  
  package:jni/src/accessors.dart [116](https://github.com/dart-lang/native/actions/runs/7035876071/job/19147336010?pr=837#step:12:117):5                                    JniAccessorWrappers.throwException
  package:jni/src/accessors.dart 16:19                                    _check
  package:jni/src/accessors.dart 92:5                                     JniClassLookupResultMethods.checkedClassRef
  package:jni/src/jni.dart 215:20                                         Jni.findClass.<fn>
  package:ffi/src/arena.dart [124](https://github.com/dart-lang/native/actions/runs/7035876071/job/19147336010?pr=837#step:12:126):31                                       using
  package:jni/src/jni.dart 213:55                                         Jni.findClass
  package:jni/src/jni.dart 221:22                                         Jni.findJClass
  test\kotlin_test\dart_only\dart_bindings\kotlin.dart 39:15              SuspendFun._class
  test\kotlin_test\dart_only\dart_bindings\kotlin.dart                    SuspendFun._class
  test\kotlin_test\dart_only\dart_bindings\kotlin.dart 50:28              new SuspendFun
  test\kotlin_test\runtime_test_registrant_dartonly_generated.dart 18:28  registerTests.<fn>.<fn>.<fn>
  package:ffi/src/arena.dart 124:31                                       using
  test\kotlin_test\runtime_test_registrant_dartonly_generated.dart 17:13  registerTests.<fn>.<fn>
```

https://github.com/dart-lang/native/actions/runs/7035876071/job/19147336010?pr=837

**Comment by dcharkes** [comment]
@HosseinYousefi have you seen this before?

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi have you seen this before?

Yes, this is related to #556. I need to fix it!

**Comment by dcharkes** [comment]
This is still or again happening:

```
❌ test/runtime_test.dart: kotlin_test Nullability Inner class (failed)
  Exception in Java: java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/Nullability
  java.lang.NoClassDefFoundError: com/github/dart_lang/jnigen/Nullability
  Caused by: java.lang.ClassNotFoundException: com.github.dart_lang.jnigen.Nullability
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
  
  package:jni/src/jni.dart 209:5                        Jni.throwException
  package:jni/src/accessors.dart 16:9                   _check
  package:jni/src/accessors.dart 110:5                  JniClassLookupResultMethods.checkedClassRef
  package:jni/src/jni.dart 197:10                       Jni.findClass
  package:jni/src/jclass.dart 17:50                     new JClass.forName
  test/kotlin_test/bindings/kotlin.dart 35751:20        Nullability._class
  test/kotlin_test/bindings/kotlin.dart                 Nullability._class
  test/kotlin_test/bindings/kotlin.dart 35785:25        Nullability.
  test/kotlin_test/runtime_test_registrant.dart 213:16  registerTests.<fn>.<fn>.testObject
  test/kotlin_test/runtime_test_registrant.dart 419:23  registerTests.<fn>.<fn>.<fn>.<fn>
  package:ffi/src/arena.dart 127:31                     using
  test/kotlin_test/runtime_test_registrant.dart 418:9   registerTests.<fn>.<fn>.<fn>
❌ test/runtime_test.dart: kotlin_test Nullability Setters (failed)
```

https://github.com/dart-lang/native/actions/runs/29008842068/job/86088182118?pr=3413
