### ISSUE TITLE
jnigen cannot find module-info

### ISSUE THREAD

**Issue by mweller83** [dart-lang/native#959]
Hi!

I'm trying to use Apache Lucene in a flutter project. So I setup this (minimal) plugin
https://github.com/mweller83/lucene_plugin
that is very similar to the pdfbox_plugin example. 
I decided to write a little wrapper in Java (to index and search documents), then generate dart bindings to be able to call it from flutter/dart. If you look into jnigen.yaml you see that I included several source_deps. I use mk_java.sh to compile my java wrapper and then generate bindings.
As long as I only use one source_deps entry everything works fine. But for all the required functionality I need to add more dependencies and then I get this error if I execute jnigen:

```Resolving dependencies in /home/maw/dev/flutter_pdf_searcher/lucene_plugin_2... 
Got dependencies in /home/maw/dev/flutter_pdf_searcher/lucene_plugin_2.
Building package executable... (1.5s)
Built jnigen:jnigen.
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) INFO: execute mvn compile --batch-mode --update-snapshots -f /home/maw/.pub-cache/hosted/pub.dev/jnigen-0.7.0/java/pom.xml
(jnigen) INFO: execute mvn -q -f ./maven_temp_GVVURL/temp_pom.xml dependency:unpack-dependencies -DexcludeTransitive=true -DoutputDirectory=../mvn_java -Dclassifier=sources
(jnigen) INFO: execute mvn -q -f ./maven_temp_DACYMW/temp_pom.xml dependency:copy-dependencies -DoutputDirectory=../mvn_jar
(jnigen) INFO: execute java -jar .dart_tool/jnigen/ApiSummarizer.jar -s jsrc/main/java/:mvn_java/ -c mvn_jar/lucene-analysis-common-9.9.2.jar:mvn_jar/lucene-core-9.9.2.jar:mvn_jar/lucene-sandbox-9.9.2.jar:mvn_jar/lucene-queries-9.9.2.jar:mvn_jar/lucene-queryparser-9.9.2.jar maw.lucene_wrapper.LuceneWrapper maw.lucene_wrapper.LuceneResult
Loading source file jsrc/main/java/maw/lucene_wrapper/LuceneWrapper.java...
Loading source file jsrc/main/java/maw/lucene_wrapper/LuceneResult.java...
mvn_java/module-info.java:20: error: module not found: org.apache.lucene.core
  requires org.apache.lucene.core;
                            ^
error: cannot access org.apache.lucene.queries.module-info
  cannot resolve modules
Note: 2 errors
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
        at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
        at com.github.dart_lang.jnigen.apisummarizer.Main.main(Main.java:142)

Fatal: Cannot generate summary: FormatException: Unexpected end of input (at character 1)

^
```

Is this a jnigen bug or am I doing something wrong?

**Comment by HosseinYousefi** [comment]
This is a known limitation of our source parser. You could instead compile the java sources and pass in the `.jar` file to jnigen.

**Comment by mweller83** [comment]
Thanks for that hint!
In fact using class_path instead of source_path in jnigen.yaml did the trick.
